// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDROQ8RTiKhmgjRFI5inqYv0F_ZdzfcAVA',
    appId: '1:525365788008:android:745f45ce5afb8482152add',
    messagingSenderId: '525365788008',
    projectId: 'two-are-one-llc-36899',
    storageBucket: 'two-are-one-llc-36899.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFpVi8oic4AUrJxqMQYEbzU3KI4ARTRw',
    appId: '1:525365788008:ios:c7f13ab6e8f36699152add',
    messagingSenderId: '525365788008',
    projectId: 'two-are-one-llc-36899',
    storageBucket: 'two-are-one-llc-36899.firebasestorage.app',
    iosBundleId: 'com.twoAreOne.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDriHKUxp5U66IiOUyHM4mkh9GuWfEs8aE',
    appId: '1:525365788008:web:8b799d7ebf6903db152add',
    messagingSenderId: '525365788008',
    projectId: 'two-are-one-llc-36899',
    authDomain: 'two-are-one-llc-36899.firebaseapp.com',
    storageBucket: 'two-are-one-llc-36899.firebasestorage.app',
    measurementId: 'G-RDQ3RJ04ZC',
  );
}
